"""Controlled sub-tag vocabulary for company enrichment (v3).

Closed list of industry sub-niches. Both Layer 1 brief parsing and Layer 2
company enrichment must draw from this list so the universe builder can match
via array overlap without vocabulary drift.

Tags are kebab-case, ASCII only, no leading/trailing whitespace.

If Gemini believes a needed tag is missing, it returns the candidate in
`EnrichmentResult.proposed_tags` instead of inventing one in `sub_tags`.
Curate periodically: review `proposed_tags` aggregates, promote good ones
here, bump PROMPT_VERSION.

Seed pass: LLM-drafted (Claude / GPT / Gemini), then human-edited.
Counts (~12 per sector): keep balanced; avoid generic terms like
"consulting" without qualifier; prefer recruiter-recognised niches.
"""

from __future__ import annotations

SUB_TAGS_BY_SECTOR: dict[str, list[str]] = {
    "Banking & Financial Services": [
        "retail-banking",
        "corporate-banking",
        "investment-banking",
        "private-banking",
        "islamic-banking",
        "sme-lending",
        "consumer-credit",
        "mortgage-financing",
        "buy-now-pay-later",
        "fintech-lending",
        "fintech-payments",
        "fintech-neobank",
        "trade-finance",
        "microfinance",
        "credit-cards",
    ],
    "Insurance": [
        "life-insurance",
        "health-insurance",
        "general-insurance",
        "reinsurance",
        "takaful",
        "insurance-brokerage",
        "marine-insurance",
        "motor-insurance",
        "property-casualty-insurance",
        "insurtech",
        "employee-benefits",
        "claims-management",
    ],
    "Capital Markets & Asset Management": [
        "asset-management",
        "wealth-management",
        "private-equity",
        "venture-capital",
        "hedge-fund",
        "sovereign-wealth-fund",
        "real-estate-fund",
        "sukuk-issuance",
        "investment-advisory",
        "brokerage-equities",
        "brokerage-fx",
        "custody-services",
        "fund-administration",
    ],
    "Real Estate Development": [
        "residential-development",
        "luxury-residential",
        "commercial-real-estate",
        "mixed-use-development",
        "master-planned-communities",
        "retail-mall-development",
        "hospitality-real-estate",
        "industrial-real-estate",
        "real-estate-brokerage",
        "facilities-management",
        "property-management",
        "proptech",
    ],
    "Construction & Engineering": [
        "general-contracting",
        "epc-contractor",
        "mep-contracting",
        "civil-infrastructure",
        "roads-bridges",
        "marine-construction",
        "interior-fitout",
        "structural-engineering",
        "architecture-design",
        "project-management-construction",
        "facade-engineering",
        "modular-construction",
    ],
    "Oil & Gas - Upstream": [
        "exploration-production",
        "offshore-drilling",
        "onshore-drilling",
        "reservoir-engineering",
        "seismic-services",
        "well-services",
        "oilfield-services",
        "subsea-engineering",
        "lng-upstream",
        "shale-tight-oil",
        "production-optimization",
        "decommissioning-upstream",
    ],
    "Oil & Gas - Downstream / Petrochemicals": [
        "refining",
        "petrochemicals",
        "polymers-plastics",
        "fertilizers",
        "lng-downstream",
        "fuel-retail",
        "lubricants-blending",
        "gas-distribution",
        "industrial-gases",
        "downstream-trading",
        "specialty-chemicals",
        "pipeline-operations",
    ],
    "Power & Utilities": [
        "power-generation-thermal",
        "renewable-solar",
        "renewable-wind",
        "renewable-hydro",
        "nuclear-power",
        "power-transmission",
        "power-distribution",
        "water-desalination",
        "water-treatment",
        "waste-management",
        "district-cooling",
        "energy-trading",
        "grid-tech",
    ],
    "Telecommunications": [
        "mobile-network-operator",
        "fixed-line-broadband",
        "fiber-rollout",
        "5g-infrastructure",
        "tower-infrastructure",
        "data-centers",
        "submarine-cable",
        "mvno",
        "satellite-comms",
        "iot-connectivity",
        "telecom-managed-services",
        "telecom-distribution",
    ],
    "Technology & Software": [
        "enterprise-saas",
        "cloud-infrastructure",
        "cybersecurity",
        "data-analytics",
        "ai-ml-platform",
        "ecommerce-platform",
        "fintech-software",
        "healthtech-software",
        "edtech-software",
        "devtools",
        "it-services-systems-integration",
        "hardware-iot",
        "ar-vr",
        "blockchain-crypto",
    ],
    "Retail & Consumer Goods": [
        "fashion-apparel",
        "luxury-retail",
        "grocery-supermarket",
        "consumer-electronics",
        "home-furnishings",
        "beauty-cosmetics",
        "jewelry-watches",
        "automotive-retail",
        "fmcg-manufacturing",
        "food-beverage-brand",
        "ecommerce-retailer",
        "department-store",
        "specialty-retail",
        "mobile-devices",
    ],
    "Hospitality, Travel & Tourism": [
        "hotels-luxury",
        "hotels-midscale",
        "serviced-apartments",
        "restaurants-fb",
        "qsr-fast-casual",
        "cafes-coffee",
        "destination-management",
        "tour-operator",
        "travel-agency-otas",
        "cruise-yachting",
        "events-conferences",
        "theme-parks-attractions",
    ],
    "Healthcare & Pharmaceuticals": [
        "hospitals-multispecialty",
        "specialty-clinics",
        "primary-care",
        "diagnostic-imaging",
        "laboratory-services",
        "pharmaceutical-manufacturing",
        "pharma-distribution",
        "medical-devices",
        "biotech-research",
        "telehealth",
        "pharmacy-retail",
        "home-healthcare",
    ],
    "Logistics, Shipping & Ports": [
        "freight-forwarding",
        "3pl-warehousing",
        "last-mile-delivery",
        "shipping-lines",
        "port-operations",
        "cold-chain-logistics",
        "express-courier",
        "supply-chain-management",
        "customs-brokerage",
        "intermodal-rail",
        "trucking-road-freight",
        "logistics-tech",
    ],
    "Aviation & Aerospace": [
        "passenger-airline",
        "cargo-airline",
        "low-cost-carrier",
        "airport-operations",
        "ground-handling",
        "mro-aircraft-maintenance",
        "aircraft-leasing",
        "aerospace-manufacturing",
        "defense-aviation",
        "satellite-services",
        "drone-uav",
        "business-aviation",
    ],
    "Manufacturing & Industrial": [
        "steel-metals",
        "aluminum-smelting",
        "cement-building-materials",
        "glass-ceramics",
        "industrial-equipment",
        "automotive-components",
        "food-processing",
        "textiles-apparel-manufacturing",
        "packaging",
        "heavy-machinery",
        "electrical-equipment",
        "industrial-automation",
        "contract-manufacturing",
    ],
    "Media, Entertainment & Advertising": [
        "broadcasting-tv",
        "radio",
        "print-publishing",
        "digital-publishing",
        "advertising-agency",
        "media-buying",
        "pr-communications",
        "film-production",
        "music-recording",
        "gaming-esports",
        "streaming-platforms",
        "influencer-creator-economy",
    ],
    "Education & Training": [
        "k12-schools",
        "higher-education-university",
        "vocational-training",
        "edtech-platforms",
        "corporate-training",
        "language-training",
        "professional-certifications",
        "test-prep",
        "tutoring-services",
        "early-childhood-education",
        "online-courses-mooc",
        "executive-education",
    ],
    "Professional Services": [
        "management-consulting",
        "strategy-consulting",
        "audit-assurance",
        "tax-advisory",
        "legal-services",
        "executive-search",
        "staffing-recruitment",
        "real-estate-advisory",
        "marketing-research",
        "engineering-consulting",
        "actuarial-services",
        "outsourcing-bpo",
    ],
    "Conglomerates / Family Groups / Holdings": [
        "family-business-group",
        "diversified-holding",
        "investment-holding",
        "trading-group",
        "industrial-conglomerate",
        "ruling-family-holding",
        "sovereign-holding",
        "regional-distributor-group",
    ],
}


def all_sub_tags() -> list[str]:
    """Flat list of all canonical sub-tags across sectors."""
    out: list[str] = []
    for tags in SUB_TAGS_BY_SECTOR.values():
        out.extend(tags)
    return out


SUB_TAGS: set[str] = set(all_sub_tags())
"""Canonical set for O(1) validation."""
